--Todos os dados
SELECT * FROM SENSORES_FARMTECH;

--Total de irrigações acionadas
SELECT 
  SUM(IRRIGACAO_ATIVA) AS TOTAL_IRRIGACOES,
  COUNT(*) AS TOTAL_LEITURAS
FROM SENSORES_FARMTECH;

--Média geral de todas as variáveis
SELECT 
  ROUND(AVG(UMIDADE), 2)     AS MEDIA_UMIDADE,
  ROUND(AVG(FOSFORO_P), 2)   AS MEDIA_FOSFORO,
  ROUND(AVG(POTASSIO_K), 2)  AS MEDIA_POTASSIO,
  ROUND(AVG(PH), 2)          AS MEDIA_PH,
  ROUND(AVG(TEMPERATURA), 2) AS MEDIA_TEMPERATURA,
  ROUND(AVG(CHUVA_MM), 2)    AS MEDIA_CHUVA
FROM SENSORES_FARMTECH;

--Leituras com solo seco (umidade abaixo de 40%)
SELECT * FROM SENSORES_FARMTECH
WHERE UMIDADE < 40
ORDER BY UMIDADE ASC;

--pH fora do ideal (ideal: 6.0 a 7.0)
SELECT * FROM SENSORES_FARMTECH
WHERE PH < 6.0 OR PH > 7.0
ORDER BY PH;

--Dias com chuva forte (acima de 20mm)
SELECT DATA_HORA, CHUVA_MM, UMIDADE, IRRIGACAO_ATIVA
FROM SENSORES_FARMTECH
WHERE CHUVA_MM > 20
ORDER BY CHUVA_MM DESC;

--Máximos e mínimos de cada sensor
SELECT
  MAX(UMIDADE) AS MAX_UMIDADE,   MIN(UMIDADE) AS MIN_UMIDADE,
  MAX(PH)      AS MAX_PH,        MIN(PH)      AS MIN_PH,
  MAX(TEMPERATURA) AS MAX_TEMP,  MIN(TEMPERATURA) AS MIN_TEMP
FROM SENSORES_FARMTECH;
